### ISSUE TITLE
"The value '126' of 'authKey' is not expected. Expected value is '256.'"

### ISSUE THREAD

**Issue by hendinejad** [vik-borisov/TelegramClient#41]
Hi,

I started using the library with .Net 4.6 and VS2015. I write a test code according to quick start, but actually I have stopped in first steps.

Here is my code:

```
        public static int ApiId = ;
        public static string ApiHash = "";
        public static string ServerAddress = "";
        public static int ServerPort = ;

        static void Main(string[] args)
        {
            var client = ClientFactory.BuildClient(ApiId, ApiHash, ServerAddress, ServerPort);
            client.ConnectService.ConnectAsync().Wait();    <--- The line with exception!
```

Here is the exception:
{"The value '126' of 'authKey' is not expected. Expected value is '256.'"}
and this is the stack trace:

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at ViraConsoleGram.Program.Main(String[] args) in C:\Users\hendi\Documents\Visual Studio 2015\Projects\Viragram\ViraConsoleGram\Program.cs:line 26
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

I'll appreciate if anyone can help me with the issue!

Regards,

**Comment by vik-borisov** [comment]
Hello, @hendinejad!
Please email me yours ApiId, ApiHash, ServerAddress, ServerPort

**Comment by DuanTranHuy** [comment]
i got this too

**Comment by vik-borisov** [comment]
@hendinejad 
Please email me yours ApiId, ApiHash, ServerAddress, ServerPort

**Comment by geniosar** [comment]
When the problem will be fix? I have the same problem =(

**Comment by vik-borisov** [comment]
@geniosar hello!
To reproduce the problem needs an example.
also try to delete the session.dat file
