### ISSUE TITLE
PHONE_MIGRATE_4 error on connection

### ISSUE THREAD

**Issue by d3ullist** [vik-borisov/TelegramClient#42]
System.InvalidOperationException
  HResult=0x80131509
  Message=PHONE_MIGRATE_4
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TelegramClient.Core.ApiServies.SenderService.<SendAndRecieve>d__10.MoveNext() in D:\Repos\Other\TelegramClient\src\TelegramClient.Core\ApiServies\SenderService.cs:line 44
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TelegramClient.Core.ApiServies.SenderService.<SendRequestAsync>d__9`1.MoveNext() in D:\Repos\Other\TelegramClient\src\TelegramClient.Core\ApiServies\SenderService.cs:line 28
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at TelegramClient.Core.ApiServies.AuthApiService.<SendCodeRequestAsync>d__21.MoveNext() in D:\Repos\Other\TelegramClient\src\TelegramClient.Core\ApiServies\AuthApiService.cs:line 120
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp1.Program.<Start>d__6.MoveNext() in C:\Users\incri\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 21
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ConsoleApp1.Program.Main(String[] args) in C:\Users\incri\source\repos\ConsoleApp1\ConsoleApp1\Program.cs:line 15

**Comment by daniel18aus** [comment]
I get this issue to. It seems whatever number you pass into IsPhoneRegisteredAsync or SendCodeRequestAsync will just give you a MIGRATE_X error. I'm using the TelegramClient 0.3.58

**Comment by daniel18aus** [comment]
Following this fixed it for me: https://github.com/sochix/TLSharp/issues/17#issuecomment-156845729

**Comment by daniel18aus** [comment]
@d3ullist

**Comment by RiddlerKnight** [comment]
I got PHONE_MIGRATE_5 when call 
`Client.AuthService.SendCodeRequestAsync(PhoneNumber);`

**Comment by vik-borisov** [comment]
I just fixed the error handling USER_MIGRATE_X and PHONE_MIGRATE_X. Update the library to the latest version
