### ISSUE TITLE
ConnectionStateUpdate event

### ISSUE THREAD

**Issue by KoalaBear84** [vik-borisov/TelegramClient#47]
Now that I can reconnect without reauthenticating I see the following issue.

It stops listening to updates after X hours or so. And it looks like there is no way to see that it is disconnected so I can reconnect.

What is the best way to handle this? Thanks!

**Comment by OleksiyMoroz** [comment]
@KoalaBear84 
use manual update logic
helped for me, app works more than 24 hours and updates receiving still

**Comment by KoalaBear84** [comment]
I don't think that is a good idea, I would like to have the messages realtime, and polling all contacts (60 or so) does not seem like a good idea.

I also see that after the updates stop, restarting the app does not work, no more updates at all. I have to authenticate again.

Ahh, I see. I think you mean:
`var currentState = await client.UpdatesService.GetCurrentState();`
`var updates = await client.UpdatesService.GetUpdates(currentState);`

But still prefer that it just does not stop receiving updates :)

**Comment by OleksiyMoroz** [comment]
@KoalaBear84 
you can run it in the loop with few seconds delay, I think it's more stable and good performance solution for server 
this way i use few days old session and receiving updates normally

**Comment by iicaisin1** [comment]
@KoalaBear84 
I was having the same issues. This should be mostly addressed in pull request #55  and #56.

**Comment by KoalaBear84** [comment]
Thanks @iicaisin1 
It looks like the strange problems are fixed now, the timeouts etc. 👍 
Will try to let it run for a long time again to test if it doesn't get stuck anymore, that would be very great.

**Comment by KoalaBear84** [comment]
Noooooooooo. It still gets stuck with 0.4.73 :(

```
2018-02-04 20:12:52.3255  [1]  INFO Program.Main Started
*** more updates
2018-02-04 21:20:27.3404 [34]  INFO Program.ProcessMessage
*** the end, still waiting here
```

**Comment by vik-borisov** [comment]
@KoalaBear84 
[Attach the logger](https://github.com/vik-borisov/TelegramClient/wiki/How-to-attach-a-logger) and give me the full logs

**Comment by KoalaBear84** [comment]
Yes. I finally have a full log from the beginning to the end! 40.7MB.

Timeline:
- Started at 2018-02-05 15:37:11,165
- Last update receive in application at 2018-02-06 03:03:41,213 (Deleted message, the event type is not the problem, I get enough deleted messages and update after that):
```
2018-02-06 03:03:41,213 [50] DEBUG TelegramClient.Core.Network.RecieveHandlers.UpdatesRecieveHandler.? - Recieve Updates 
{"Update":{"ChannelId":1074945601,"Messages":{"Items":[9682]},"Pts":28989,"PtsCount":1},"Date":1517882458}
```
- After this there are 3 more "Recieve Updates" within the following 200ms, and then it is silence without a real clue for me
- At the end there is an error

Some 'highlights' / warning / errors:
```
2018-02-05 15:37:11,165 [1] DEBUG TelegramClient.Core.Sessions.FileSessionStoreProvider.? - Load session for sessionTag = session.dat
2018-02-05 15:37:13,171 [6] DEBUG TelegramClient.Core.Network.MtProtoSendService.? - Send message with Id = 6519079307376066568 and seqNo = 19126
2018-02-05 15:38:13,258 [10] WARN  TelegramClient.Core.Network.Confirm.ConfirmationRecieveService.? - Message confirmation timed out for messageid '6519079307376066568'
2018-02-05 15:44:16,542 [3] ERROR TelegramClient.Core.Network.Recieve.ResponseResultService.? - Callback for request with Id 6519080820471234916
2018-02-05 15:48:13,856 [23] WARN  TelegramClient.Core.Network.Recieve.ResponseResultService.? - Message response result timed out for messageid '6519081886977884680'
```

Half our before the last update in application:
```
2018-02-06 00:34:46,935 [35] WARN  TelegramClient.Core.Network.Confirm.ConfirmationRecieveService.? - Message confirmation timed out for messageid '6519217578362036940'
2018-02-06 02:33:49,136 [14] ERROR TelegramClient.Core.Network.Recieve.RecievingService.? - Receive message failed. Reconnecting
System.IO.IOException: Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Tcp.TcpService.<Read>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Tcp.TcpTransport.<Receieve>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Recieve.RecievingService.<StartRecievingTask>d__35.MoveNext()
2018-02-06 02:33:49,200 [14] DEBUG TelegramClient.Core.Network.MtProtoSendService.? - Send message with Id = 6519248512029319892 and seqNo = 19325
2018-02-06 02:33:49,201 [49] DEBUG TelegramClient.Core.Network.Tcp.TcpTransport.? - Sending message with seq_no 0
2018-02-06 02:33:50,362 [14] DEBUG TelegramClient.Core.Sessions.FileSessionStoreProvider.? - Save session into session.dat
2018-02-06 02:33:50,449 [60] DEBUG TelegramClient.Core.Network.Tcp.TcpTransport.? - Recieve message with seq_no 0
2018-02-06 02:33:50,449 [60] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Receive message with remote id: 6519248517369224193
2018-02-06 02:33:50,449 [60] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Try handle response for object: OpenTl.Schema.TBadServerSalt 
{"BadMsgId":6519248512029319892,"BadMsgSeqno":19325,"ErrorCode":48,"NewServerSalt":4516790443182382803}
2018-02-06 02:33:50,449 [60] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Handler found - TelegramClient.Core.Network.RecieveHandlers.BadServerSaltRecieveHandler
2018-02-06 02:33:50,449 [60] INFO  TelegramClient.Core.Network.RecieveHandlers.BadServerSaltRecieveHandler.? - Bad server sault detected! message id = 6519248512029319892 
2018-02-06 02:33:50,449 [49] DEBUG TelegramClient.Core.Network.Confirm.ConfirmationSendService.? - Sending confirmation for messages 6519248517369224193
```

Some more clues?
```
2018-02-06 02:38:06,733 [14] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Try handle response for object: OpenTl.Schema.TRpcResult 
{"ReqMsgId":6519161194576627716,"Result":{"ErrorCode":400,"ErrorMessageAsBinary":"UEVFUl9JRF9JTlZBTElE","ErrorMessage":"PEER_ID_INVALID"}}
2018-02-06 02:38:06,733 [14] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Handler found - TelegramClient.Core.Network.RecieveHandlers.RpcResultRecieveHandler
```

And after that a lot of these, maybe no problem!
```
2018-02-06 02:41:26,978 [14] ERROR TelegramClient.Core.Network.Recieve.RecievingService.? - Cannot handle object: OpenTl.Schema.TMsgNewDetailedInfo 
{"AnswerMsgId":6519099496855771137,"Bytes":1216,"Status":0}
2018-02-06 02:41:26,978 [14] DEBUG TelegramClient.Core.Network.Recieve.RecievingService.? - Try handle response for object: OpenTl.Schema.TMsgNewDetailedInfo 
{"AnswerMsgId":6519099496855772161,"Bytes":1216,"Status":0}
```

The final error?
```
2018-02-06 05:03:44,244 [50] ERROR TelegramClient.Core.Network.Recieve.RecievingService.? - Receive message failed. Reconnecting
System.IO.IOException: Unable to transfer data on the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Tcp.TcpService.<Read>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Tcp.TcpTransport.<Receieve>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Recieve.RecievingService.<StartRecievingTask>d__35.MoveNext()
```

Haha. As I create this comment it shows some signs of life again two hours later:
`2018-02-06 07:03:49,313 [50] ERROR TelegramClient.Core.Network.Recieve.RecievingService.? - Receive message failed. Reconnecting`

Counts.
DEBUG, Recieve Updates: 5812 times
DEBUG, Sending message with: 6594 times
DEBUG, Sending confirmation for messages: 6484 times
WARN, Message confirmation timed out for messageid: 6514 times
WARN, Message response result timed out for messageid: 108 times
ERROR, Callback for request with Id: 105 times

Thanks for all! I will send logs via Telegram to u. :)

**Comment by vik-borisov** [comment]
@KoalaBear84 I analyzed the logs and found errors. Please update the package and try again using the logs
