### ISSUE TITLE
Bad Server Sault Detected

### ISSUE THREAD

**Issue by ghost** [vik-borisov/TelegramClient#52]
I am getting say 20 messages "Bad server sault detected! message id = x" at a particular time and then don't get them again for a bit. Is this a problem and has it stopped receiving when I get this message?

Also, a typo on sault 👍

**Comment by vik-borisov** [comment]
@danextras 
You need an example code.
The exception is processed in the most recent library update for all requests/.

**Comment by ghost** [comment]
I am not getting an exception it is just going directly onto the console via Log4Net. Are you using Log4Net also and it is just picking up the settings?

I'm also getting the following error when getting all topics for a user:

System.NotSupportedException: Specified method is not supported.
   at OpenTl.Schema.Serialization.Serializer.DeserializeObject(BinaryReader reader, TypeInfo propertyTypeInfo)
   at OpenTl.Schema.Serialization.Serializer.Deserialize(BinaryReader binaryReader, TypeInfo typeInfo)
   at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(BinaryReader reader, SerializationMetadata metadata)
   at OpenTl.Schema.Serialization.Serializer.DeserializeObject(BinaryReader reader, TypeInfo propertyTypeInfo)
   at TelegramClient.Core.Network.Recieve.GZipPackedHandler.HandleGZipPacked(TgZipPacked obj)
   at TelegramClient.Core.Network.RecieveHandlers.RpcResultRecieveHandler.HandleResponce(IObject obj)
   at TelegramClient.Core.Network.Recieve.RecievingService.ProcessReceivedMessage(IObject obj)
   at TelegramClient.Core.Network.Recieve.RecievingService.<StartRecievingTask>d__24.MoveNext()

**Comment by ghost** [comment]
That was with the latest version .70 of TelegramClient and latest version of OpenTL.Schema

**Comment by vik-borisov** [comment]
> System.NotSupportedException: Specified method is not supported.
at OpenTl.Schema.Serialization.Serializer.DeserializeObject(BinaryReader reader, TypeInfo propertyTypeInfo)
at OpenTl.Schema.Serialization.Serializer.Deserialize(BinaryReader binaryReader, TypeInfo typeInfo)
at OpenTl.Schema.Serialization.Serializators.ObjectTypes.IObjectSerializer.Deserialize(BinaryReader reader, SerializationMetadata metadata)
at OpenTl.Schema.Serialization.Serializer.DeserializeObject(BinaryReader reader, TypeInfo propertyTypeInfo)
at TelegramClient.Core.Network.Recieve.GZipPackedHandler.HandleGZipPacked(TgZipPacked obj)
at TelegramClient.Core.Network.RecieveHandlers.RpcResultRecieveHandler.HandleResponce(IObject obj)
at TelegramClient.Core.Network.Recieve.RecievingService.ProcessReceivedMessage(IObject obj)
at TelegramClient.Core.Network.Recieve.RecievingService.d__24.MoveNext()

@danextras I fixed it in OpenTl.Schema. Update the package please.

**Comment by ghost** [comment]
I've updated to the latest TelegramClient 0.4.71 and 0.73.40 and now get:

2018-02-01 16:46:16,875 - Receive message failed

System.InvalidOperationException: invalid checksum! skip
   at TelegramClient.Core.Network.Tcp.TcpTransport.<Receieve>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at TelegramClient.Core.Network.Tcp.TcpTransport.<Receieve>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.Recieve.RecievingService.<StartRecievingTask>d__24.MoveNext()

**Comment by ghost** [comment]
It doesn't seem to do anything after this so it seems broken.

**Comment by vik-borisov** [comment]
@danextras try to remove the session.dat file.

**Comment by ghost** [comment]
Yes I tried that first.

**Comment by vik-borisov** [comment]
@danextras 
[attach logger](https://github.com/vik-borisov/TelegramClient/wiki/Attach-logger). 
And send me the logs

**Comment by vik-borisov** [comment]
fixed
