### ISSUE TITLE
Reconnect issue?

### ISSUE THREAD

**Issue by KoalaBear84** [vik-borisov/TelegramClient#54]
As my path to try to have a workaround for https://github.com/vik-borisov/TelegramClient/issues/53 I tried reconnecting. After doing that I get an internal error from the library.

Code:
```
private static async void Reconnect(ITelegramClient client)
{
	Log.Info("Logging out");
	await client.ConnectService.LogOut();
	Log.Info("Logged out");
	Log.Info("Connecting");
	await client.ConnectService.ConnectAsync();
	Log.Info("Connected");
}
```

Exception:
"Couldn't read the packet length"
```
   at TelegramClient.Core.Network.Tcp.TcpTransport.<Receieve>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.Network.MtProtoPlainSender.<SendAndReceive>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.ConnectApiService.<DoAuthentication>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.ConnectApiService.<ConnectAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramCryptoClient.Program.<Reconnect>d__56.MoveNext() in C:\Repositories\Koala\trunk\TelegramCryptoClient\TelegramCryptoClient\Program.cs:line 450
```

Hmm, I used to get another exception, but that is probably when the connection is already bad or so because of other issue mentioned above.

Other exception:
```
2018-01-25 05:05:29.1033 [25] ERROR Program.CheckUpdates System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TelegramClient.Core.Network.MtProtoSendService.PrepareToSend(IObject obj, Int64& mesId)
   at TelegramClient.Core.Network.MtProtoSendService.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendAndRecieve>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendRequestAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.UpdatesApiService.<GetUpdates>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at TelegramCryptoClient.Program.<CheckUpdates>d__58.MoveNext() in C:\Repositories\Koala\trunk\TelegramCryptoClient\TelegramCryptoClient\Program.cs:line 465
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at TelegramClient.Core.Network.MtProtoSendService.PrepareToSend(IObject obj, Int64& mesId)
   at TelegramClient.Core.Network.MtProtoSendService.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendAndRecieve>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendRequestAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.UpdatesApiService.<GetUpdates>d__5.MoveNext()<---
 System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at TelegramClient.Core.Network.MtProtoSendService.PrepareToSend(IObject obj, Int64& mesId)
   at TelegramClient.Core.Network.MtProtoSendService.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendAndRecieve>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendRequestAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.UpdatesApiService.<GetUpdates>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at TelegramCryptoClient.Program.<CheckUpdates>d__58.MoveNext() in C:\Repositories\Koala\trunk\TelegramCryptoClient\TelegramCryptoClient\Program.cs:line 465
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at TelegramClient.Core.Network.MtProtoSendService.PrepareToSend(IObject obj, Int64& mesId)
   at TelegramClient.Core.Network.MtProtoSendService.<Send>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendAndRecieve>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.SenderService.<SendRequestAsync>d__13`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at TelegramClient.Core.ApiServies.UpdatesApiService.<GetUpdates>d__5.MoveNext()<---
```

**Comment by vik-borisov** [comment]
@KoalaBear84 
Does reconnect work?

**Comment by ghost** [comment]
How do you know which dcId to use? How also do you know when the connection has gone bad as I don't see any methods in the connect service to get the current state

**Comment by vik-borisov** [comment]
@danextras 
after connecting the server sends the nearest ds

**Comment by ghost** [comment]
Which framework call is this in? I couldn't see anything like that in the BuildClient or ConnectService.ConnectAsync methods about a dc id.

**Comment by vik-borisov** [comment]
It is the internal structure of the library
https://github.com/vik-borisov/TelegramClient/blob/d03da6de2becf55895ef438c4bb26bbe4e5a04ae/src/TelegramClient.Core/ApiServies/ConnectApiService.cs#L103

**Comment by ghost** [comment]
Ok, when you said "does the reconnect work" earlier, I figured you meant the method ConnectService.ReconnectToDcAsync which takes the dcId. 

Since you are only ever attached to one dc at a time and _dcOptions is private, can you make another method for reconnect that doesn't receive the dc id and just reconnects to the dc that we were last connected to?

**Comment by vik-borisov** [comment]
@danextras it is not a good idea.
let the library engage in systems activities

**Comment by ghost** [comment]
Yes I would prefer if the library would catch that error that KoalaBear84
mentioned and reconnect automatically.
